Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 99

Layout/TrailingBlankLines:
  Enabled: false

Style/EmptyMethod:
  Enabled: false