AllCops:
  TargetRubyVersion: '2.5.1'

Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 99
  IgnoredPatterns: ['(\A|\s)#']

Layout/TrailingBlankLines:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Naming/VariableNumber:
  Enabled: false